#!/bin/sh
#
# To enable this hook, rename this file to "prepare-commit-msg".

num=1
git status --porcelain |
grep -v -e '^ . ' -e '^?? ' |
sed 's/^.. //' |
sed -e 's/^"//' -e 's/"$//' |
while read line; do
	sed -i -e "${num}i\\
$line
" "$1"
	num=$(($num + 1))
done

#if test -n "$GIT_PREFIX" ; then
#	sed -i -e "1i $GIT_PREFIX" "$1"
#fi

#echo '#' >> "$1"
#echo '# Hooks:' >> "$1"
#echo '#' "$0" "$@" >> "$1"
#echo '#' >> "$1"
#env | sed 's/^/# /' >> "$1"
